name: "Fetch Site Headers"
description: "Fetches the headers for a given site"

inputs:
  site:
    description: "The site to fetch headers for"
    required: true
    default: "https://www.build.com/"

outputs:
  site-version:
    description: "The version of the site"
    value: ${{ steps.get-headers.outputs.site-version }}

runs:
  using: composite
  steps:
    - name: Fetch Headers
      id: get-headers
      uses: actions/github-script@v6
      with:
        script: |
          const run = require('.github/scripts/get-headers.js');
          await run({ core })
        # script: |
        #   const site = "${{ inputs.site }}";
        #   fetch(site).then((res) => {
        #     const siteVersion = res.headers.get("X-Fergy-App-Version");
        #     console.log({ headers: res.headers, siteVersion })
        #     core.setOutput("site-version", siteVersion);
        #   }).catch((err) => {
        #     console.log(err);
        #   });
