name: "WPT Runner"
description: Full WebPageTest Runner

inputs:
  packages-access-token:
    description: PACKAGES_ACCESS_TOKEN from parent workflow
    required: true
  wpt-token:
    description: API key for google PSI
    required: true
  slack-webhook:
    description: slack webhook url
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          rm package*
          cd  .github/scripts
          npm i webpagetest
        shell: bash
    - name: Single WPT Run
      uses: ./.github/actions/run-wpt/single-runner
      id: single-wpt-runner
      with:
        packages-access-token: ${{ inputs.packages-access-token }}
        wpt-token: ${{ inputs.wpt-token }}
        slack-webhook: ${{ inputs.slack-webhook }}
        device: MOBILE
        page-slug: product/summary/433454
        page-name: Categories Page
