name: "WPT Runner"

on:
  pull_request:

jobs:
  run-wpt:
    name: Run WPT
    runs-on: ubuntu-latest
    outputs:
      wpt: ${{ steps.wpt-runner.outputs.wpt }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-wpt
        id: wpt-runner
        with:
          packages-access-token: ${{ secrets.GITHUB_TOKEN }}
          wpt-token: ${{ secrets.WEBPAGETEST_API_KEY }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          device: MOBILE
          page-slug: /product/summary/433454
          page-name: Categories Page
