name: "WPT Runner"

on:
  pull_request:

jobs:
  run-wpt:
    name: Run WPT
    runs-on: ubuntu-latest
    outputs:
      wpt: ${{ steps.wpt-runner.outputs.wpt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/get-headers
        with:
          site: "https://www.build.com"
      # - uses: ./.github/actions/run-wpt
      #   id: wpt-runner
      #   with:
      #     packages-access-token: ${{ secrets.GITHUB_TOKEN }}
      #     wpt-token: ${{ secrets.WEBPAGETEST_API_KEY }}
      #     slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
